<?php
// Liste des pays, en français
// Adapté de http://fr.wikipedia.org/wiki/ISO_3166-1
// Dernière maj : 19/04/2013

return array(
    array('num', 'alpha3', 'alpha2', 'name', 'fullname'),
    array('533', 'ABW', 'AW', 'Aruba', 'ARUBA'),
    array('004', 'AFG', 'AF', 'Afghanistan', 'AFGHANISTAN'),
    array('024', 'AGO', 'AO', 'Angola', 'ANGOLA'),
    array('660', 'AIA', 'AI', 'Anguilla', 'ANGUILLA'),
    array('248', 'ALA', 'AX', 'Åland', 'ÅLAND, ÎLES'),
    array('008', 'ALB', 'AL', 'Albanie', 'ALBANIE'),
    array('020', 'AND', 'AD', 'Andorre', 'ANDORRE'),
    array('784', 'ARE', 'AE', 'Émirats arabes unis', 'ÉMIRATS ARABES UNIS'),
    array('032', 'ARG', 'AR', 'Argentine', 'ARGENTINE'),
    array('051', 'ARM', 'AM', 'Arménie', 'ARMÉNIE'),
    array('016', 'ASM', 'AS', 'Samoa américaines', 'SAMOA AMÉRICAINES'),
    array('010', 'ATA', 'AQ', 'Antarctique', 'ANTARCTIQUE'),
    array('260', 'ATF', 'TF', 'Terres australes et antarctiques françaises', 'TERRES AUSTRALES FRANÇAISES'),
    array('028', 'ATG', 'AG', 'Antigua-et-Barbuda', 'ANTIGUA-ET-BARBUDA'),
    array('036', 'AUS', 'AU', 'Australie', 'AUSTRALIE'),
    array('040', 'AUT', 'AT', 'Autriche', 'AUTRICHE'),
    array('031', 'AZE', 'AZ', 'Azerbaïdjan', 'AZERBAÏDJAN'),
    array('108', 'BDI', 'BI', 'Burundi', 'BURUNDI'),
    array('056', 'BEL', 'BE', 'Belgique', 'BELGIQUE'),
    array('204', 'BEN', 'BJ', 'Bénin', 'BÉNIN'),
    array('535', 'BES', 'BQ', 'Bonaire, Saint-Eustache et Saba', 'BONAIRE, SAINT-EUSTACHE ET SABA'),
    array('854', 'BFA', 'BF', 'Burkina Faso', 'BURKINA FASO'),
    array('050', 'BGD', 'BD', 'Bangladesh', 'BANGLADESH'),
    array('100', 'BGR', 'BG', 'Bulgarie', 'BULGARIE'),
    array('048', 'BHR', 'BH', 'Bahreïn', 'BAHREÏN'),
    array('044', 'BHS', 'BS', 'Bahamas', 'BAHAMAS'),
    array('070', 'BIH', 'BA', 'Bosnie-Herzégovine', 'BOSNIE-HERZÉGOVINE'),
    array('652', 'BLM', 'BL', 'Saint-Barthélemy', 'SAINT-BARTHÉLEMY'),
    array('112', 'BLR', 'BY', 'Biélorussie', 'BÉLARUS'),
    array('084', 'BLZ', 'BZ', 'Belize', 'BELIZE'),
    array('060', 'BMU', 'BM', 'Bermudes', 'BERMUDES'),
    array('068', 'BOL', 'BO', 'Bolivie', 'BOLIVIE, ÉTAT PLURINATIONAL DE'),
    array('076', 'BRA', 'BR', 'Brésil', 'BRÉSIL'),
    array('052', 'BRB', 'BB', 'Barbade', 'BARBADE'),
    array('096', 'BRN', 'BN', 'Brunei', 'BRUNÉI DARUSSALAM'),
    array('064', 'BTN', 'BT', 'Bhoutan', 'BHOUTAN'),
    array('074', 'BVT', 'BV', 'Île Bouvet', 'BOUVET, ÎLE'),
    array('072', 'BWA', 'BW', 'Botswana', 'BOTSWANA'),
    array('140', 'CAF', 'CF', 'République centrafricaine', 'CENTRAFRICAINE, RÉPUBLIQUE'),
    array('124', 'CAN', 'CA', 'Canada', 'CANADA'),
    array('166', 'CCK', 'CC', 'Îles Cocos', 'COCOS (KEELING), ÎLES'),
    array('756', 'CHE', 'CH', 'Suisse', 'SUISSE'),
    array('152', 'CHL', 'CL', 'Chili', 'CHILI'),
    array('156', 'CHN', 'CN', 'Chine', 'CHINE'),
    array('384', 'CIV', 'CI', 'Côte d\'Ivoire', 'CÔTE D\'IVOIRE'),
    array('120', 'CMR', 'CM', 'Cameroun', 'CAMEROUN'),
    array('180', 'COD', 'CD', 'République démocratique du Congo', 'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU'),
    array('178', 'COG', 'CG', 'République du Congo', 'CONGO'),
    array('184', 'COK', 'CK', 'Îles Cook', 'COOK, ÎLES'),
    array('170', 'COL', 'CO', 'Colombie', 'COLOMBIE'),
    array('174', 'COM', 'KM', 'Comores', 'COMORES'),
    array('132', 'CPV', 'CV', 'Cap-Vert', 'CAP-VERT'),
    array('188', 'CRI', 'CR', 'Costa Rica', 'COSTA RICA'),
    array('192', 'CUB', 'CU', 'Cuba', 'CUBA'),
    array('531', 'CUW', 'CW', 'Curaçao', 'CURAÇAO'),
    array('162', 'CXR', 'CX', 'Île Christmas', 'CHRISTMAS, ÎLE'),
    array('136', 'CYM', 'KY', 'Îles Caïmans', 'CAÏMANES, ÎLES'),
    array('196', 'CYP', 'CY', 'Chypre', 'CHYPRE'),
    array('203', 'CZE', 'CZ', 'République tchèque', 'TCHÈQUE, RÉPUBLIQUE'),
    array('276', 'DEU', 'DE', 'Allemagne', 'ALLEMAGNE'),
    array('262', 'DJI', 'DJ', 'Djibouti', 'DJIBOUTI'),
    array('212', 'DMA', 'DM', 'Dominique', 'DOMINIQUE'),
    array('208', 'DNK', 'DK', 'Danemark', 'DANEMARK'),
    array('214', 'DOM', 'DO', 'République dominicaine', 'DOMINICAINE, RÉPUBLIQUE'),
    array('012', 'DZA', 'DZ', 'Algérie', 'ALGÉRIE'),
    array('218', 'ECU', 'EC', 'Équateur', 'ÉQUATEUR'),
    array('818', 'EGY', 'EG', 'Égypte', 'ÉGYPTE'),
    array('232', 'ERI', 'ER', 'Érythrée', 'ÉRYTHRÉE'),
    array('732', 'ESH', 'EH', 'Sahara occidental', 'SAHARA OCCIDENTAL'),
    array('724', 'ESP', 'ES', 'Espagne', 'ESPAGNE'),
    array('233', 'EST', 'EE', 'Estonie', 'ESTONIE'),
    array('231', 'ETH', 'ET', 'Éthiopie', 'ÉTHIOPIE'),
    array('246', 'FIN', 'FI', 'Finlande', 'FINLANDE'),
    array('242', 'FJI', 'FJ', 'Fidji', 'FIDJI'),
    array('238', 'FLK', 'FK', 'Îles Malouines', 'FALKLAND, ÎLES (MALVINAS)'),
    array('250', 'FRA', 'FR', 'France', 'FRANCE'),
    array('234', 'FRO', 'FO', 'Îles Féroé', 'FÉROÉ, ÎLES'),
    array('583', 'FSM', 'FM', 'Micronésie', 'MICRONÉSIE, ÉTATS FÉDÉRÉS DE'),
    array('266', 'GAB', 'GA', 'Gabon', 'GABON'),
    array('826', 'GBR', 'GB', 'Royaume-Uni', 'ROYAUME-UNI'),
    array('268', 'GEO', 'GE', 'Géorgie', 'GÉORGIE'),
    array('831', 'GGY', 'GG', 'Guernesey', 'GUERNESEY'),
    array('288', 'GHA', 'GH', 'Ghana', 'GHANA'),
    array('292', 'GIB', 'GI', 'Gibraltar', 'GIBRALTAR'),
    array('324', 'GIN', 'GN', 'Guinée', 'GUINÉE'),
    array('312', 'GLP', 'GP', 'Guadeloupe', 'GUADELOUPE'),
    array('270', 'GMB', 'GM', 'Gambie', 'GAMBIE'),
    array('624', 'GNB', 'GW', 'Guinée-Bissau', 'GUINÉE-BISSAU'),
    array('226', 'GNQ', 'GQ', 'Guinée équatoriale', 'GUINÉE ÉQUATORIALE'),
    array('300', 'GRC', 'GR', 'Grèce', 'GRÈCE'),
    array('308', 'GRD', 'GD', 'Grenade', 'GRENADE'),
    array('304', 'GRL', 'GL', 'Groenland', 'GROENLAND'),
    array('320', 'GTM', 'GT', 'Guatemala', 'GUATEMALA'),
    array('254', 'GUF', 'GF', 'Guyane', 'GUYANE FRANÇAISE'),
    array('316', 'GUM', 'GU', 'Guam', 'GUAM'),
    array('328', 'GUY', 'GY', 'Guyana', 'GUYANA'),
    array('344', 'HKG', 'HK', 'Hong Kong', 'HONG KONG'),
    array('334', 'HMD', 'HM', 'Îles Heard-et-MacDonald', 'HEARD, ÎLE ET MCDONALD, ÎLES'),
    array('340', 'HND', 'HN', 'Honduras', 'HONDURAS'),
    array('191', 'HRV', 'HR', 'Croatie', 'CROATIE'),
    array('332', 'HTI', 'HT', 'Haïti', 'HAÏTI'),
    array('348', 'HUN', 'HU', 'Hongrie', 'HONGRIE'),
    array('360', 'IDN', 'ID', 'Indonésie', 'INDONÉSIE'),
    array('833', 'IMN', 'IM', 'Île de Man', ''),
    array('356', 'IND', 'IN', 'Inde', 'INDE'),
    array('086', 'IOT', 'IO', 'Territoire britannique de l\'océan Indien', 'OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L\''),
    array('372', 'IRL', 'IE', 'Irlande', 'IRLANDE'),
    array('364', 'IRN', 'IR', 'Iran', 'IRAN, RÉPUBLIQUE ISLAMIQUE D\''),
    array('368', 'IRQ', 'IQ', 'Irak', 'IRAQ'),
    array('352', 'ISL', 'IS', 'Islande', 'ISLANDE'),
    array('376', 'ISR', 'IL', 'Israël', 'ISRAËL'),
    array('380', 'ITA', 'IT', 'Italie', 'ITALIE'),
    array('388', 'JAM', 'JM', 'Jamaïque', 'JAMAÏQUE'),
    array('832', 'JEY', 'JE', 'Jersey', 'JERSEY'),
    array('400', 'JOR', 'JO', 'Jordanie', 'JORDANIE'),
    array('392', 'JPN', 'JP', 'Japon', 'JAPON'),
    array('398', 'KAZ', 'KZ', 'Kazakhstan', 'KAZAKHSTAN'),
    array('404', 'KEN', 'KE', 'Kenya', 'KENYA'),
    array('417', 'KGZ', 'KG', 'Kirghizistan', 'KIRGHIZISTAN'),
    array('116', 'KHM', 'KH', 'Cambodge', 'CAMBODGE'),
    array('296', 'KIR', 'KI', 'Kiribati', 'KIRIBATI'),
    array('659', 'KNA', 'KN', 'Saint-Christophe-et-Niévès', 'SAINT-KITTS-ET-NEVIS'),
    array('410', 'KOR', 'KR', 'Corée du Sud', 'CORÉE, RÉPUBLIQUE DE'),
    array('414', 'KWT', 'KW', 'Koweït', 'KOWEÏT'),
    array('418', 'LAO', 'LA', 'Laos', 'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE'),
    array('422', 'LBN', 'LB', 'Liban', 'LIBAN'),
    array('430', 'LBR', 'LR', 'Liberia', 'LIBÉRIA'),
    array('434', 'LBY', 'LY', 'Libye', 'LIBYE'),
    array('662', 'LCA', 'LC', 'Sainte-Lucie', 'SAINTE-LUCIE'),
    array('438', 'LIE', 'LI', 'Liechtenstein', 'LIECHTENSTEIN'),
    array('144', 'LKA', 'LK', 'Sri Lanka', 'SRI LANKA'),
    array('426', 'LSO', 'LS', 'Lesotho', 'LESOTHO'),
    array('440', 'LTU', 'LT', 'Lituanie', 'LITUANIE'),
    array('442', 'LUX', 'LU', 'Luxembourg', 'LUXEMBOURG'),
    array('428', 'LVA', 'LV', 'Lettonie', 'LETTONIE'),
    array('446', 'MAC', 'MO', 'Macao', 'MACAO'),
    array('663', 'MAF', 'MF', 'Saint-Martin', 'SAINT-MARTIN (PARTIE FRANÇAISE)'),
    array('504', 'MAR', 'MA', 'Maroc', 'MAROC'),
    array('492', 'MCO', 'MC', 'Monaco', 'MONACO'),
    array('498', 'MDA', 'MD', 'Moldavie', 'MOLDOVA'),
    array('450', 'MDG', 'MG', 'Madagascar', 'MADAGASCAR'),
    array('462', 'MDV', 'MV', 'Maldives', 'MALDIVES'),
    array('484', 'MEX', 'MX', 'Mexique', 'MEXIQUE'),
    array('584', 'MHL', 'MH', 'Marshall', 'MARSHALL, ÎLES'),
    array('807', 'MKD', 'MK', 'Macédoine', 'MACÉDOINE, L\'EX-RÉPUBLIQUE YOUGOSLAVE DE'),
    array('466', 'MLI', 'ML', 'Mali', 'MALI'),
    array('470', 'MLT', 'MT', 'Malte', 'MALTE'),
    array('104', 'MMR', 'MM', 'Birmanie', 'MYANMAR'),
    array('499', 'MNE', 'ME', 'Monténégro', 'MONTÉNÉGRO'),
    array('496', 'MNG', 'MN', 'Mongolie', 'MONGOLIE'),
    array('580', 'MNP', 'MP', 'Îles Mariannes du Nord', 'MARIANNES DU NORD, ÎLES'),
    array('508', 'MOZ', 'MZ', 'Mozambique', 'MOZAMBIQUE'),
    array('478', 'MRT', 'MR', 'Mauritanie', 'MAURITANIE'),
    array('500', 'MSR', 'MS', 'Montserrat', 'MONTSERRAT'),
    array('474', 'MTQ', 'MQ', 'Martinique', 'MARTINIQUE'),
    array('480', 'MUS', 'MU', 'Maurice', 'MAURICE'),
    array('454', 'MWI', 'MW', 'Malawi', 'MALAWI'),
    array('458', 'MYS', 'MY', 'Malaisie', 'MALAISIE'),
    array('175', 'MYT', 'YT', 'Mayotte', 'MAYOTTE'),
    array('516', 'NAM', 'NA', 'Namibie', 'NAMIBIE'),
    array('540', 'NCL', 'NC', 'Nouvelle-Calédonie', 'NOUVELLE-CALÉDONIE'),
    array('562', 'NER', 'NE', 'Niger', 'NIGER'),
    array('574', 'NFK', 'NF', 'Île Norfolk', 'NORFOLK, ÎLE'),
    array('566', 'NGA', 'NG', 'Nigeria', 'NIGÉRIA'),
    array('558', 'NIC', 'NI', 'Nicaragua', 'NICARAGUA'),
    array('570', 'NIU', 'NU', 'Niue', 'NIUÉ'),
    array('528', 'NLD', 'NL', 'Pays-Bas', 'PAYS-BAS'),
    array('578', 'NOR', 'NO', 'Norvège', 'NORVÈGE'),
    array('524', 'NPL', 'NP', 'Népal', 'NÉPAL'),
    array('520', 'NRU', 'NR', 'Nauru', 'NAURU'),
    array('554', 'NZL', 'NZ', 'Nouvelle-Zélande', 'NOUVELLE-ZÉLANDE'),
    array('512', 'OMN', 'OM', 'Oman', 'OMAN'),
    array('586', 'PAK', 'PK', 'Pakistan', 'PAKISTAN'),
    array('591', 'PAN', 'PA', 'Panama', 'PANAMA'),
    array('612', 'PCN', 'PN', 'Îles Pitcairn', 'PITCAIRN'),
    array('604', 'PER', 'PE', 'Pérou', 'PÉROU'),
    array('608', 'PHL', 'PH', 'Philippines', 'PHILIPPINES'),
    array('585', 'PLW', 'PW', 'Palaos', 'PALAOS'),
    array('598', 'PNG', 'PG', 'Papouasie-Nouvelle-Guinée', 'PAPOUASIE-NOUVELLE-GUINÉE'),
    array('616', 'POL', 'PL', 'Pologne', 'POLOGNE'),
    array('630', 'PRI', 'PR', 'Porto Rico', 'PORTO RICO'),
    array('408', 'PRK', 'KP', 'Corée du Nord', 'CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE'),
    array('620', 'PRT', 'PT', 'Portugal', 'PORTUGAL'),
    array('600', 'PRY', 'PY', 'Paraguay', 'PARAGUAY'),
    array('275', 'PSE', 'PS', 'Palestine', 'ÉTAT PALESTINIEN'),
    array('258', 'PYF', 'PF', 'Polynésie française', 'POLYNÉSIE FRANÇAISE'),
    array('634', 'QAT', 'QA', 'Qatar', 'QATAR'),
    array('638', 'REU', 'RE', 'La Réunion', 'RÉUNION'),
    array('642', 'ROU', 'RO', 'Roumanie', 'ROUMANIE'),
    array('643', 'RUS', 'RU', 'Russie', 'RUSSIE, FÉDÉRATION DE'),
    array('646', 'RWA', 'RW', 'Rwanda', 'RWANDA'),
    array('682', 'SAU', 'SA', 'Arabie saoudite', 'ARABIE SAOUDITE'),
    array('729', 'SDN', 'SD', 'Soudan', 'SOUDAN'),
    array('686', 'SEN', 'SN', 'Sénégal', 'SÉNÉGAL'),
    array('702', 'SGP', 'SG', 'Singapour', 'SINGAPOUR'),
    array('239', 'SGS', 'GS', 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD'),
    array('654', 'SHN', 'SH', 'Sainte-Hélène, Ascension et Tristan da Cunha|', 'SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA'),
    array('744', 'SJM', 'SJ', 'Svalbard et île Jan Mayen', 'SVALBARD ET ÎLE JAN MAYEN'),
    array('090', 'SLB', 'SB', 'Salomon', 'SALOMON, ÎLES'),
    array('694', 'SLE', 'SL', 'Sierra Leone', 'SIERRA LEONE'),
    array('222', 'SLV', 'SV', 'Salvador', 'EL SALVADOR'),
    array('674', 'SMR', 'SM', 'Saint-Marin', 'SAINT-MARIN'),
    array('706', 'SOM', 'SO', 'Somalie', 'SOMALIE'),
    array('666', 'SPM', 'PM', 'Saint-Pierre-et-Miquelon', 'SAINT-PIERRE-ET-MIQUELON'),
    array('688', 'SRB', 'RS', 'Serbie', 'SERBIE'),
    array('728', 'SSD', 'SS', 'Soudan du Sud', 'SOUDAN DU SUD'),
    array('678', 'STP', 'ST', 'Sao Tomé-et-Principe', 'SAO TOMÉ-ET-PRINCIPE'),
    array('740', 'SUR', 'SR', 'Suriname', 'SURINAME'),
    array('703', 'SVK', 'SK', 'Slovaquie', 'SLOVAQUIE'),
    array('705', 'SVN', 'SI', 'Slovénie', 'SLOVÉNIE'),
    array('752', 'SWE', 'SE', 'Suède', 'SUÈDE'),
    array('748', 'SWZ', 'SZ', 'Swaziland', 'SWAZILAND'),
    array('534', 'SXM', 'SX', 'Saint-Martin', 'SAINT-MARTIN (PARTIE NÉERLANDAISE)'),
    array('690', 'SYC', 'SC', 'Seychelles', 'SEYCHELLES'),
    array('760', 'SYR', 'SY', 'Syrie', 'SYRIENNE, RÉPUBLIQUE ARABE'),
    array('796', 'TCA', 'TC', 'Îles Turques-et-Caïques', 'TURKS ET CAÏQUES, ÎLES'),
    array('148', 'TCD', 'TD', 'Tchad', 'TCHAD'),
    array('768', 'TGO', 'TG', 'Togo', 'TOGO'),
    array('764', 'THA', 'TH', 'Thaïlande', 'THAÏLANDE'),
    array('762', 'TJK', 'TJ', 'Tadjikistan', 'TADJIKISTAN'),
    array('772', 'TKL', 'TK', 'Tokelau', 'TOKELAU'),
    array('795', 'TKM', 'TM', 'Turkménistan', 'TURKMÉNISTAN'),
    array('626', 'TLS', 'TL', 'Timor oriental', 'TIMOR-LESTE'),
    array('776', 'TON', 'TO', 'Tonga', 'TONGA'),
    array('780', 'TTO', 'TT', 'Trinité-et-Tobago', 'TRINITÉ-ET-TOBAGO'),
    array('788', 'TUN', 'TN', 'Tunisie', 'TUNISIE'),
    array('792', 'TUR', 'TR', 'Turquie', 'TURQUIE'),
    array('798', 'TUV', 'TV', 'Tuvalu', 'TUVALU'),
    array('158', 'TWN', 'TW', 'Taïwan', 'TAÏWAN, PROVINCE DE CHINE'),
    array('834', 'TZA', 'TZ', 'Tanzanie', 'TANZANIE, RÉPUBLIQUE UNIE DE'),
    array('800', 'UGA', 'UG', 'Ouganda', 'OUGANDA'),
    array('804', 'UKR', 'UA', 'Ukraine', 'UKRAINE'),
    array('581', 'UMI', 'UM', 'Îles mineures éloignées des États-Unis', 'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS'),
    array('858', 'URY', 'UY', 'Uruguay', 'URUGUAY'),
    array('840', 'USA', 'US', 'États-Unis', 'ÉTATS-UNIS'),
    array('860', 'UZB', 'UZ', 'Ouzbékistan', 'OUZBÉKISTAN'),
    array('336', 'VAT', 'VA', 'Vatican', 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)'),
    array('670', 'VCT', 'VC', 'Saint-Vincent-et-les-Grenadines', 'SAINT-VINCENT-ET-LES GRENADINES'),
    array('862', 'VEN', 'VE', 'Venezuela', 'VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU'),
    array('092', 'VGB', 'VG', 'Îles Vierges britanniques', 'ÎLES VIERGES BRITANNIQUES'),
    array('850', 'VIR', 'VI', 'Îles Vierges des États-Unis', 'ÎLES VIERGES DES ÉTATS-UNIS'),
    array('704', 'VNM', 'VN', 'Viêt Nam', 'VIET NAM'),
    array('548', 'VUT', 'VU', 'Vanuatu', 'VANUATU'),
    array('876', 'WLF', 'WF', 'Wallis-et-Futuna', 'WALLIS-ET-FUTUNA'),
    array('882', 'WSM', 'WS', 'Samoa', 'SAMOA'),
    array('887', 'YEM', 'YE', 'Yémen', 'YÉMEN'),
    array('710', 'ZAF', 'ZA', 'Afrique du Sud', 'AFRIQUE DU SUD'),
    array('894', 'ZMB', 'ZM', 'Zambie', 'ZAMBIE'),
    array('716', 'ZWE', 'ZW', 'Zimbabwe', 'ZIMBABWE'),
);