<?php
// Liste des langues, en français
// Adapté de http://www.loc.gov/standards/iso639-2/php/French_list.php
// Dernière maj : 19/04/2013

return array(
    array('alpha3', 'alpha2', 'name'),
    array('aar', 'aa', 'afar'),
    array('abk', 'ab', 'abkhaze'),
    array('ace', '', 'aceh'),
    array('ach', '', 'acoli'),
    array('ada', '', 'adangme'),
    array('ady', '', 'adyghé'),
    array('afa', '', 'afro-asiatiques, langues'),
    array('afh', '', 'afrihili'),
    array('afr', 'af', 'afrikaans'),
    array('ain', '', 'aïnou'),
    array('aka', 'ak', 'akan'),
    array('akk', '', 'akkadien'),
    array('alb', 'sq', 'albanais'),
    array('ale', '', 'aléoute'),
    array('alg', '', 'algonquines, langues'),
    array('alt', '', 'altai du Sud'),
    array('amh', 'am', 'amharique'),
    array('ang', '', 'anglo-saxon (ca.450-1100)'),
    array('anp', '', 'angika'),
    array('apa', '', 'apaches, langues'),
    array('ara', 'ar', 'arabe'),
    array('arc', '', 'araméen d\'empire (700-300 BCE)'),
    array('arg', 'an', 'aragonais'),
    array('arm', 'hy', 'arménien'),
    array('arn', '', 'mapuce'),
    array('arn', '', 'mapuche'),
    array('arn', '', 'mapudungun'),
    array('arp', '', 'arapaho'),
    array('art', '', 'artificielles, langues'),
    array('arw', '', 'arawak'),
    array('asm', 'as', 'assamais'),
    array('ast', '', 'asturien'),
    array('ast', '', 'asturoléonais'),
    array('ast', '', 'bable'),
    array('ast', '', 'léonais'),
    array('ath', '', 'athapascanes, langues'),
    array('aus', '', 'australiennes, langues'),
    array('ava', 'av', 'avar'),
    array('ave', 'ae', 'avestique'),
    array('awa', '', 'awadhi'),
    array('aym', 'ay', 'aymara'),
    array('aze', 'az', 'azéri'),
    array('bad', '', 'banda, langues'),
    array('bai', '', 'bamiléké, langues'),
    array('bak', 'ba', 'bachkir'),
    array('bal', '', 'baloutchi'),
    array('bam', 'bm', 'bambara'),
    array('ban', '', 'balinais'),
    array('baq', 'eu', 'basque'),
    array('bas', '', 'basa'),
    array('bat', '', 'baltes, langues'),
    array('bej', '', 'bedja'),
    array('bel', 'be', 'biélorusse'),
    array('bem', '', 'bemba'),
    array('ben', 'bn', 'bengali'),
    array('ber', '', 'berbères, langues'),
    array('bho', '', 'bhojpuri'),
    array('bih', 'bh', 'langues biharis'),
    array('bik', '', 'bikol'),
    array('bin', '', 'bini'),
    array('bin', '', 'edo'),
    array('bis', 'bi', 'bichlamar'),
    array('bla', '', 'blackfoot'),
    array('bnt', '', 'bantou, langues'),
    array('bos', 'bs', 'bosniaque'),
    array('bra', '', 'braj'),
    array('bre', 'br', 'breton'),
    array('btk', '', 'batak, langues'),
    array('bua', '', 'bouriate'),
    array('bug', '', 'bugi'),
    array('bul', 'bg', 'bulgare'),
    array('bur', 'my', 'birman'),
    array('byn', '', 'bilen'),
    array('byn', '', 'blin'),
    array('cad', '', 'caddo'),
    array('cai', '', 'amérindiennes de l\'Amérique centrale, langues'),
    array('car', '', 'carib'),
    array('car', '', 'galibi'),
    array('car', '', 'karib'),
    array('cat', 'ca', 'catalan'),
    array('cat', 'ca', 'valencien'),
    array('cau', '', 'caucasiennes, langues'),
    array('ceb', '', 'cebuano'),
    array('cel', '', 'celtes, langues'),
    array('cel', '', 'celtiques, langues'),
    array('cha', 'ch', 'chamorro'),
    array('chb', '', 'chibcha'),
    array('che', 'ce', 'tchétchène'),
    array('chg', '', 'djaghataï'),
    array('chi', 'zh', 'chinois'),
    array('chk', '', 'chuuk'),
    array('chm', '', 'mari'),
    array('chn', '', 'chinook, jargon'),
    array('cho', '', 'choctaw'),
    array('chp', '', 'chipewyan'),
    array('chr', '', 'cherokee'),
    array('chu', 'cu', 'slavon d\'église'),
    array('chu', 'cu', 'slavon liturgique'),
    array('chu', 'cu', 'vieux bulgare'),
    array('chu', 'cu', 'vieux slave'),
    array('chv', 'cv', 'tchouvache'),
    array('chy', '', 'cheyenne'),
    array('cmc', '', 'chames, langues'),
    array('cop', '', 'copte'),
    array('cor', 'kw', 'cornique'),
    array('cos', 'co', 'corse'),
    array('cpe', '', 'créoles et pidgins basés sur l\'anglais'),
    array('cpf', '', 'créoles et pidgins basés sur le français'),
    array('cpp', '', 'créoles et pidgins basés sur le portugais'),
    array('cre', 'cr', 'cree'),
    array('crh', '', 'tatar de Crimé'),
    array('crp', '', 'créoles et pidgins'),
    array('csb', '', 'kachoube'),
    array('cus', '', 'couchitiques, langues'),
    array('cze', 'cs', 'tchèque'),
    array('dak', '', 'dakota'),
    array('dan', 'da', 'danois'),
    array('dar', '', 'dargwa'),
    array('day', '', 'dayak, langues'),
    array('del', '', 'delaware'),
    array('den', '', 'esclave (athapascan)'),
    array('dgr', '', 'dogrib'),
    array('din', '', 'dinka'),
    array('div', 'dv', 'maldivien'),
    array('doi', '', 'dogri'),
    array('dra', '', 'dravidiennes, langues'),
    array('dsb', '', 'bas-sorabe'),
    array('dua', '', 'douala'),
    array('dum', '', 'néerlandais moyen (ca. 1050-1350)'),
    array('dut', 'nl', 'flamand'),
    array('dut', 'nl', 'néerlandais'),
    array('dyu', '', 'dioula'),
    array('dzo', 'dz', 'dzongkha'),
    array('efi', '', 'efik'),
    array('egy', '', 'égyptien'),
    array('eka', '', 'ekajuk'),
    array('elx', '', 'élamite'),
    array('eng', 'en', 'anglais'),
    array('enm', '', 'anglais moyen (1100-1500)'),
    array('epo', 'eo', 'espéranto'),
    array('est', 'et', 'estonien'),
    array('ewe', 'ee', 'éwé'),
    array('ewo', '', 'éwondo'),
    array('fan', '', 'fang'),
    array('fao', 'fo', 'féroïen'),
    array('fat', '', 'fanti'),
    array('fij', 'fj', 'fidjien'),
    array('fil', '', 'filipino'),
    array('fil', '', 'pilipino'),
    array('fin', 'fi', 'finnois'),
    array('fiu', '', 'finno-ougriennes, langues'),
    array('fon', '', 'fon'),
    array('fre', 'fr', 'français'),
    array('frm', '', 'français moyen (1400-1600)'),
    array('fro', '', 'français ancien (842-ca.1400)'),
    array('frr', '', 'frison septentrional'),
    array('frs', '', 'frison oriental'),
    array('fry', 'fy', 'frison occidental'),
    array('ful', 'ff', 'peul'),
    array('fur', '', 'frioulan'),
    array('gaa', '', 'ga'),
    array('gay', '', 'gayo'),
    array('gba', '', 'gbaya'),
    array('gem', '', 'germaniques, langues'),
    array('geo', 'ka', 'géorgien'),
    array('ger', 'de', 'allemand'),
    array('gez', '', 'guèze'),
    array('gil', '', 'kiribati'),
    array('gla', 'gd', 'gaélique'),
    array('gla', 'gd', 'gaélique écossais'),
    array('gle', 'ga', 'irlandais'),
    array('glg', 'gl', 'galicien'),
    array('glv', 'gv', 'mannois'),
    array('glv', 'gv', 'manx'),
    array('gmh', '', 'allemand, moyen haut (ca. 1050-1500)'),
    array('goh', '', 'allemand, vieux haut (ca. 750-1050)'),
    array('gon', '', 'gond'),
    array('gor', '', 'gorontalo'),
    array('got', '', 'gothique'),
    array('grb', '', 'grebo'),
    array('grc', '', 'grec ancien (jusqu\'à 1453)'),
    array('gre', 'el', 'grec moderne (après 1453)'),
    array('grn', 'gn', 'guarani'),
    array('gsw', '', 'alémanique'),
    array('gsw', '', 'alsacien'),
    array('gsw', '', 'suisse alémanique'),
    array('guj', 'gu', 'goudjrati'),
    array('gwi', '', 'gwich\'in'),
    array('hai', '', 'haida'),
    array('hat', 'ht', 'créole haïtien'),
    array('hat', 'ht', 'haïtien'),
    array('hau', 'ha', 'haoussa'),
    array('haw', '', 'hawaïen'),
    array('heb', 'he', 'hébreu'),
    array('her', 'hz', 'herero'),
    array('hil', '', 'hiligaynon'),
    array('him', '', 'langues himachalis'),
    array('him', '', 'langues paharis occidentales'),
    array('hin', 'hi', 'hindi'),
    array('hit', '', 'hittite'),
    array('hmn', '', 'hmong'),
    array('hmo', 'ho', 'hiri motu'),
    array('hrv', 'hr', 'croate'),
    array('hsb', '', 'haut-sorabe'),
    array('hun', 'hu', 'hongrois'),
    array('hup', '', 'hupa'),
    array('iba', '', 'iban'),
    array('ibo', 'ig', 'igbo'),
    array('ice', 'is', 'islandais'),
    array('ido', 'io', 'ido'),
    array('iii', 'ii', 'yi de Sichuan'),
    array('ijo', '', 'ijo, langues'),
    array('iku', 'iu', 'inuktitut'),
    array('ile', 'ie', 'interlingue'),
    array('ilo', '', 'ilocano'),
    array('ina', 'ia', 'interlingua (langue auxiliaire internationale)'),
    array('inc', '', 'indo-aryennes, langues'),
    array('ind', 'id', 'indonésien'),
    array('ine', '', 'indo-européennes, langues'),
    array('inh', '', 'ingouche'),
    array('ipk', 'ik', 'inupiaq'),
    array('ira', '', 'iraniennes, langues'),
    array('iro', '', 'iroquoises, langues'),
    array('ita', 'it', 'italien'),
    array('jav', 'jv', 'javanais'),
    array('jbo', '', 'lojban'),
    array('jpn', 'ja', 'japonais'),
    array('jpr', '', 'judéo-persan'),
    array('jrb', '', 'judéo-arabe'),
    array('kaa', '', 'karakalpak'),
    array('kab', '', 'kabyle'),
    array('kac', '', 'jingpho'),
    array('kac', '', 'kachin'),
    array('kal', 'kl', 'groenlandais'),
    array('kam', '', 'kamba'),
    array('kan', 'kn', 'kannada'),
    array('kar', '', 'karen, langues'),
    array('kas', 'ks', 'kashmiri'),
    array('kau', 'kr', 'kanouri'),
    array('kaw', '', 'kawi'),
    array('kaz', 'kk', 'kazakh'),
    array('kbd', '', 'kabardien'),
    array('kha', '', 'khasi'),
    array('khi', '', 'khoïsan, langues'),
    array('khm', 'km', 'khmer central'),
    array('kho', '', 'khotanais'),
    array('kho', '', 'sakan'),
    array('kik', 'ki', 'kikuyu'),
    array('kin', 'rw', 'rwanda'),
    array('kir', 'ky', 'kirghiz'),
    array('kmb', '', 'kimbundu'),
    array('kok', '', 'konkani'),
    array('kom', 'kv', 'kom'),
    array('kon', 'kg', 'kongo'),
    array('kor', 'ko', 'coréen'),
    array('kos', '', 'kosrae'),
    array('kpe', '', 'kpellé'),
    array('krc', '', 'karatchai balkar'),
    array('krl', '', 'carélien'),
    array('kro', '', 'krou, langues'),
    array('kru', '', 'kurukh'),
    array('kua', 'kj', 'kuanyama'),
    array('kua', 'kj', 'kwanyama'),
    array('kum', '', 'koumyk'),
    array('kur', 'ku', 'kurde'),
    array('kut', '', 'kutenai'),
    array('lad', '', 'judéo-espagnol'),
    array('lah', '', 'lahnda'),
    array('lam', '', 'lamba'),
    array('lao', 'lo', 'lao'),
    array('lat', 'la', 'latin'),
    array('lav', 'lv', 'letton'),
    array('lez', '', 'lezghien'),
    array('lim', 'li', 'limbourgeois'),
    array('lin', 'ln', 'lingala'),
    array('lit', 'lt', 'lituanien'),
    array('lol', '', 'mongo'),
    array('loz', '', 'lozi'),
    array('ltz', 'lb', 'luxembourgeois'),
    array('lua', '', 'luba-lulua'),
    array('lub', 'lu', 'luba-katanga'),
    array('lug', 'lg', 'ganda'),
    array('lui', '', 'luiseno'),
    array('lun', '', 'lunda'),
    array('luo', '', 'luo (Kenya et Tanzanie)'),
    array('lus', '', 'Lushai'),
    array('mac', 'mk', 'macédonien'),
    array('mad', '', 'madourais'),
    array('mag', '', 'magahi'),
    array('mah', 'mh', 'marshall'),
    array('mai', '', 'maithili'),
    array('mak', '', 'makassar'),
    array('mal', 'ml', 'malayalam'),
    array('man', '', 'mandingue'),
    array('mao', 'mi', 'maori'),
    array('map', '', 'austronésiennes, langues'),
    array('mar', 'mr', 'marathe'),
    array('mas', '', 'massaï'),
    array('may', 'ms', 'malais'),
    array('mdf', '', 'moksa'),
    array('mdr', '', 'mandar'),
    array('men', '', 'mendé'),
    array('mga', '', 'irlandais moyen (900-1200)'),
    array('mic', '', 'mi\'kmaq'),
    array('mic', '', 'micmac'),
    array('min', '', 'minangkabau'),
    array('mis', '', 'langues non codées'),
    array('mkh', '', 'môn-khmer, langues'),
    array('mlg', 'mg', 'malgache'),
    array('mlt', 'mt', 'maltais'),
    array('mnc', '', 'mandchou'),
    array('mni', '', 'manipuri'),
    array('mno', '', 'manobo, langues'),
    array('moh', '', 'mohawk'),
    array('mon', 'mn', 'mongol'),
    array('mos', '', 'moré'),
    array('mul', '', 'multilingue'),
    array('mun', '', 'mounda, langues'),
    array('mus', '', 'muskogee'),
    array('mwl', '', 'mirandais'),
    array('mwr', '', 'marvari'),
    array('myn', '', 'maya, langues'),
    array('myv', '', 'erza'),
    array('nah', '', 'nahuatl, langues'),
    array('nai', '', 'nord-amérindiennes, langues'),
    array('nap', '', 'napolitain'),
    array('nau', 'na', 'nauruan'),
    array('nav', 'nv', 'navaho'),
    array('nbl', 'nr', 'ndébélé du Sud'),
    array('nde', 'nd', 'ndébélé du Nord'),
    array('ndo', 'ng', 'ndonga'),
    array('nds', '', 'allemand, bas'),
    array('nds', '', 'bas allemand'),
    array('nds', '', 'bas saxon'),
    array('nds', '', 'saxon, bas'),
    array('nep', 'ne', 'népalais'),
    array('new', '', 'nepal bhasa'),
    array('new', '', 'newari'),
    array('nia', '', 'nias'),
    array('nic', '', 'nigéro-kordofaniennes, langues'),
    array('niu', '', 'niué'),
    array('nno', 'nn', 'norvégien nynorsk'),
    array('nno', 'nn', 'nynorsk, norvégien'),
    array('nob', 'nb', 'bokmål, norvégien'),
    array('nob', 'nb', 'norvégien bokmål'),
    array('nog', '', 'nogaï'),
    array('nog', '', 'nogay'),
    array('non', '', 'norrois, vieux'),
    array('nor', 'no', 'norvégien'),
    array('nqo', '', 'n\'ko'),
    array('nso', '', 'pedi'),
    array('nso', '', 'sepedi'),
    array('nso', '', 'sotho du Nord'),
    array('nub', '', 'nubiennes, langues'),
    array('nwc', '', 'newari classique'),
    array('nya', 'ny', 'chewa'),
    array('nya', 'ny', 'chichewa'),
    array('nya', 'ny', 'nyanja'),
    array('nym', '', 'nyamwezi'),
    array('nyn', '', 'nyankolé'),
    array('nyo', '', 'nyoro'),
    array('nzi', '', 'nzema'),
    array('oci', 'oc', 'occitan (après 1500)'),
    array('oji', 'oj', 'ojibwa'),
    array('ori', 'or', 'oriya'),
    array('orm', 'om', 'galla'),
    array('osa', '', 'osage'),
    array('oss', 'os', 'ossète'),
    array('ota', '', 'turc ottoman (1500-1928)'),
    array('oto', '', 'otomi, langues'),
    array('paa', '', 'papoues, langues'),
    array('pag', '', 'pangasinan'),
    array('pal', '', 'pahlavi'),
    array('pam', '', 'pampangan'),
    array('pan', 'pa', 'pendjabi'),
    array('pap', '', 'papiamento'),
    array('pau', '', 'palau'),
    array('peo', '', 'perse, vieux (ca. 600-400 av. J.-C.)'),
    array('per', 'fa', 'persan'),
    array('phi', '', 'philippines, langues'),
    array('phn', '', 'phénicien'),
    array('pli', 'pi', 'pali'),
    array('pol', 'pl', 'polonais'),
    array('pon', '', 'pohnpei'),
    array('por', 'pt', 'portugais'),
    array('pra', '', 'prâkrit, langues'),
    array('pro', '', 'occitan ancien (jusqu\'à 1500)'),
    array('pro', '', 'provençal ancien (jusqu\'à 1500)'),
    array('pus', 'ps', 'pachto'),
    array('qaa', '', 'réservée à l\'usage local'),
    array('que', 'qu', 'quechua'),
    array('raj', '', 'rajasthani'),
    array('rap', '', 'rapanui'),
    array('rar', '', 'maori des îles Cook'),
    array('rar', '', 'rarotonga'),
    array('roa', '', 'romanes, langues'),
    array('roh', 'rm', 'romanche'),
    array('rom', '', 'tsigane'),
    array('rum', 'ro', 'moldave'),
    array('rum', 'ro', 'roumain'),
    array('run', 'rn', 'rundi'),
    array('rup', '', 'aroumain'),
    array('rup', '', 'macédo-roumain'),
    array('rus', 'ru', 'russe'),
    array('sad', '', 'sandawe'),
    array('sag', 'sg', 'sango'),
    array('sah', '', 'iakoute'),
    array('sai', '', 'sud-amérindiennes, langues'),
    array('sal', '', 'salishennes, langues'),
    array('sam', '', 'samaritain'),
    array('san', 'sa', 'sanskrit'),
    array('sas', '', 'sasak'),
    array('sat', '', 'santal'),
    array('scn', '', 'sicilien'),
    array('sco', '', 'écossais'),
    array('sel', '', 'selkoupe'),
    array('sem', '', 'sémitiques, langues'),
    array('sga', '', 'irlandais ancien (jusqu\'à 900)'),
    array('sgn', '', 'langues des signes'),
    array('shn', '', 'chan'),
    array('sid', '', 'sidamo'),
    array('sin', 'si', 'singhalais'),
    array('sio', '', 'sioux, langues'),
    array('sit', '', 'sino-tibétaines, langues'),
    array('sla', '', 'slaves, langues'),
    array('slo', 'sk', 'slovaque'),
    array('slv', 'sl', 'slovène'),
    array('sma', '', 'sami du Sud'),
    array('sme', 'se', 'sami du Nord'),
    array('smi', '', 'sames, langues'),
    array('smj', '', 'sami de Lule'),
    array('smn', '', 'sami d\'Inari'),
    array('smo', 'sm', 'samoan'),
    array('sms', '', 'sami skolt'),
    array('sna', 'sn', 'shona'),
    array('snd', 'sd', 'sindhi'),
    array('snk', '', 'soninké'),
    array('sog', '', 'sogdien'),
    array('som', 'so', 'somali'),
    array('son', '', 'songhai, langues'),
    array('sot', 'st', 'sotho du Sud'),
    array('spa', 'es', 'castillan'),
    array('spa', 'es', 'espagnol'),
    array('srd', 'sc', 'sarde'),
    array('srn', '', 'sranan tongo'),
    array('srp', 'sr', 'serbe'),
    array('srr', '', 'sérère'),
    array('ssa', '', 'nilo-sahariennes, langues'),
    array('ssw', 'ss', 'swati'),
    array('suk', '', 'sukuma'),
    array('sun', 'su', 'soundanais'),
    array('sus', '', 'soussou'),
    array('sux', '', 'sumérien'),
    array('swa', 'sw', 'swahili'),
    array('swe', 'sv', 'suédois'),
    array('syc', '', 'syriaque classique'),
    array('syr', '', 'syriaque'),
    array('tah', 'ty', 'tahitien'),
    array('tai', '', 'tai, langues'),
    array('tam', 'ta', 'tamoul'),
    array('tat', 'tt', 'tatar'),
    array('tel', 'te', 'télougou'),
    array('tem', '', 'temne'),
    array('ter', '', 'tereno'),
    array('tet', '', 'tetum'),
    array('tgk', 'tg', 'tadjik'),
    array('tgl', 'tl', 'tagalog'),
    array('tha', 'th', 'thaï'),
    array('tib', 'bo', 'tibétain'),
    array('tig', '', 'tigré'),
    array('tir', 'ti', 'tigrigna'),
    array('tiv', '', 'tiv'),
    array('tkl', '', 'tokelau'),
    array('tlh', '', 'klingon'),
    array('tli', '', 'tlingit'),
    array('tmh', '', 'tamacheq'),
    array('tog', '', 'tonga (Nyasa)'),
    array('ton', 'to', 'tongan (Îles Tonga)'),
    array('tpi', '', 'tok pisin'),
    array('tsi', '', 'tsimshian'),
    array('tsn', 'tn', 'tswana'),
    array('tso', 'ts', 'tsonga'),
    array('tuk', 'tk', 'turkmène'),
    array('tum', '', 'tumbuka'),
    array('tup', '', 'tupi, langues'),
    array('tur', 'tr', 'turc'),
    array('tut', '', 'altaïques, langues'),
    array('tvl', '', 'tuvalu'),
    array('twi', 'tw', 'twi'),
    array('tyv', '', 'touva'),
    array('udm', '', 'oudmourte'),
    array('uga', '', 'ougaritique'),
    array('uig', 'ug', 'ouïgour'),
    array('ukr', 'uk', 'ukrainien'),
    array('umb', '', 'umbundu'),
    array('und', '', 'indéterminée'),
    array('urd', 'ur', 'ourdou'),
    array('uzb', 'uz', 'ouszbek'),
    array('vai', '', 'vaï'),
    array('ven', 've', 'venda'),
    array('vie', 'vi', 'vietnamien'),
    array('vol', 'vo', 'volapük'),
    array('vot', '', 'vote'),
    array('wak', '', 'wakashanes, langues'),
    array('wal', '', 'wolaitta'),
    array('wal', '', 'wolaytta'),
    array('war', '', 'waray'),
    array('was', '', 'washo'),
    array('wel', 'cy', 'gallois'),
    array('wen', '', 'sorabes, langues'),
    array('wln', 'wa', 'wallon'),
    array('wol', 'wo', 'wolof'),
    array('xal', '', 'kalmouk'),
    array('xal', '', 'oïrat'),
    array('xho', 'xh', 'xhosa'),
    array('yao', '', 'yao'),
    array('yap', '', 'yapois'),
    array('yid', 'yi', 'yiddish'),
    array('yor', 'yo', 'yoruba'),
    array('ypk', '', 'yupik, langues'),
    array('zap', '', 'zapotèque'),
    array('zbl', '', 'Bliss'),
    array('zbl', '', 'symboles Bliss'),
    array('zen', '', 'zenaga'),
    array('zgh', '', 'amazighe standard marocain'),
    array('zha', 'za', 'chuang'),
    array('zha', 'za', 'zhuang'),
    array('znd', '', 'zandé, langues'),
    array('zul', 'zu', 'zoulou'),
    array('zun', '', 'zuni'),
    array('zxx', '', 'non applicable'),
    array('zxx', '', 'pas de contenu linguistique'),
    array('zza', '', 'dimili'),
    array('zza', '', 'dimli'),
    array('zza', '', 'kirdki'),
    array('zza', '', 'kirmanjki'),
    array('zza', '', 'zaza'),
    array('zza', '', 'zazaki'),
);